# main.py
from pathlib import Path
from uuid import uuid4


from graph.state import TestAutomationState
from agents.test_writer import TestWriterAgent
from tools.swagger_parser import load_swagger_file


# ----------------------------
# Example user story
# ----------------------------
USER_STORY = """
User Story: Submit Leave Request


As an employee,
I want to submit a leave request through the system,
So that my leave can be reviewed and approved by administrators.


Acceptance Criteria:
- AC1: Employee must be authenticated before submitting requests
- AC2: Employee can specify leave type, start date, end date, and number of days
- AC3: System validates that dates are in correct order (from < to)
- AC4: System validates sufficient leave balance exists
- AC5: System creates leave request with "Pending" status
- AC6: System returns success message with request ID
"""


# ----------------------------
# Example Gherkin (usually generated by Agent 2)
# ----------------------------
GHERKIN_CONTENT = """
Feature: Submit Leave Request


  Background:
    Given the employee is authenticated
    And the employee has sufficient leave balance


  Scenario: Successfully submit a valid leave request
    Given the employee is on the leave request form
    When the employee submits a leave request with:
      | type      | Annual Leave |
      | fromDate  | 2025-03-01   |
      | toDate    | 2025-03-05   |
      | days      | 5            |
    Then the system should return status code 200
    And the system should display "Leave request submitted successfully"
    And the leave request should have status "Pending"
"""


# ----------------------------
# Paths to Swagger JSON files
# ----------------------------
SWAGGER_AUTH_PATH = "examples/sample_swagger1.json"
SWAGGER_LEAVE_PATH = "examples/sample_swagger2.json"


def main():
    print("="*60)
    print("🛠 Multi-Service Test Writer Agent Test")
    print("="*60)
   
    # Step 1: Load Swagger specs
    auth_swagger = load_swagger_file(SWAGGER_AUTH_PATH)
    leave_swagger = load_swagger_file(SWAGGER_LEAVE_PATH)
   
    swagger_specs = {
        "auth": auth_swagger,
        "leave": leave_swagger
    }
   
    print(f"✅ Loaded {len(swagger_specs)} Swagger specifications")


    # Step 2: Create TestAutomationState
    state = TestAutomationState(
        workflow_id=str(uuid4()),
        service_name="refuse-leave-request",
        user_story=USER_STORY,
        swagger_specs=swagger_specs,
        gherkin_content=GHERKIN_CONTENT,
        gherkin_files=["features\refuse-leave-request_20260204_182011.feature"]
    )
   
    print(f"✅ State created for service: {state.service_name}")
    print(f"   - Swagger specs: {len(state.swagger_specs)}")
    print(f"   - Gherkin scenarios: {GHERKIN_CONTENT.count('Scenario:')}")
   
    # Step 3: Run Test Writer Agent
    agent = TestWriterAgent()
    updated_state = agent.write_tests(state)
   
    print("\n✅ Test Writer Agent finished\n")
   
    # Step 4: Show generated files
    if updated_state.test_files:
        print("📁 Generated Files:")
        for f in updated_state.test_files:
            print(f"   ✓ {f}")
   
    # Step 5: Show warnings
    if updated_state.warnings:
        print("\n⚠️ Warnings:")
        for w in updated_state.warnings[:5]:
            print(f"   - {w}")
        if len(updated_state.warnings) > 5:
            print(f"   ... and {len(updated_state.warnings)-5} more")
   
    # Step 6: Step Definitions Preview
    if "step_definitions" in updated_state.test_code:
        print("\n📝 Step Definitions Preview (first 20 lines):")
        print("-"*60)
        lines = updated_state.test_code["step_definitions"].splitlines()[:20]
        for i, line in enumerate(lines, 1):
            print(f"{i:3d} | {line}")
        if len(updated_state.test_code["step_definitions"].splitlines()) > 20:
            print("    | ...")
   
    # Step 7: Agent statistics
    test_writer_output = updated_state.get_agent_output("test_writer")
    if test_writer_output:
        print("\n📊 Test Writer Statistics:")
        output_data = test_writer_output.output_data
        print(f"   - Files generated: {output_data.get('files_generated', 0)}")
        print(f"   - Swagger specs used: {output_data.get('swagger_specs_used', 0)}")
        print(f"   - Step definitions lines: {output_data.get('step_definitions_lines', 0)}")
        print(f"   - Unique steps: {output_data.get('unique_steps_implemented', 0)}")
        print(f"   - Validation issues: {output_data.get('validation_issues', 0)}")
        print(f"   - Duration: {test_writer_output.duration_ms:.0f}ms")
   
    print("\n✅ Test Writer Agent test completed successfully!")


if __name__ == "__main__":
    main()



